# This GitLab CI configuration is used for the weekly exercies of
# the course Ohjelmointi 3/Programming 3

# For more information refer to: https://course-gitlab.tut.fi/help/ci/yaml/README.md

# We use an image based on Alpine Linux that contains
# Qt 5.9.6 and the necessary  

image: pervasivetut/alpine_qt_5.9.6:latest

# We currently only need the build stage
stages:
  - build
  - test

# Build job to see that the EX1 project is created and the project is ready for submission.
build_EX1:
  stage: build
  tags:
    - qt
  script: 
    - cd EX1/DesignByContract
    - qmake
    - make
    - make clean
  allow_failure: true
